# Site settings
title: Christopher Cooke
name: Christopher Cooke

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: GitHub
   url: https://github.com/IfThen2
 - title: StackOverflow
   url: https://stackoverflow.com/users/8088939/chris-c
 - title: LinkedIn
   url: https://www.linkedin.com/in/christopherjcooke/

#Any buzzword skills you want to include
skills:
 - Java 8
 - zTPF IBM 64-Bit Assembler (Mainframe)
 - CDI (Spring / Guice)
 - Microservices
 - JPA / Hibernate
 - Code Reviews
 - API design
 - Spring / Spring Boot / Spring MVC
 - Solace / Kafka / JMS
 - Maven
 - Ant
 - Junit 5 + Mockito
 - Bug Fixes / Production Support
 - REST
 - Technical Architecture

#Work experience is required
roles:
 - title: Software Engineer 
   start: Oct. 2019
   end: Ongoing
   employer: Retailer Web Services
   description: Serves more than 2,700 appliance, electronics, furniture and mattress retailers in North America with a complete suite of digital marketing solutions. Products include <a href="https://app.webfronts.com/login.html" taget="_blank">WebFronts</a>, <a href="https://app.retaildeck.com/" taget="_blank">RetailDeck</a>, <a href="https://www.retailerwebservices.com/webfronts-review.html" taget="_blank">WebFronts Review</a>.
 - title: Software Engineer II
   start: Apr. 2018
   end: Sept. 2019
   employer: American Express
   description: Worked on the Credit Authorizations System, the heartbeat of AMEX. Designed and implemented new stategies to remove non-essential capabilities from legacy mainframe systems.
 - title: Software Engineer III
   start: Feb. 2016
   end: Apr. 2018
   employer: American Express
   description: Severity 1 incidents, as well as high visibility emergency bridges. Participated in all aspects of product development (Requirements gathering, Design, PI Planning, etc). JUG – Led presentations and tutorials for AMEX’s Java User’s Group
 - title: Software Engineer Intern
   start: Jul. 2015
   end: Feb. 2016
   employer: American Express
   description: Learning - IBM 64-Bit z/TPF Assembler, z/Linux, and the Waterfall SDLC.	Mainframe Support – Low severity incident tickets. Mainframe Developer – Designed and implemented system monitoring tools.

#Education is required
education:
 - level: N/A
   date: Ongoing
   subject: Computer Science
   school: Paradise Valley Community College

#List of interesting Github repo/projects to include - optional
github:
 - IfThen2/https://github.com/IfThen2/dynamic-recompiler

#Stackoverflow flair is optional
stackoverflow:
   profileurl: https://stackoverflow.com/users/8088939/chris-c

intro: |
  I am a software engineer who thrives by working with others who love what they are doing. Getting my start at American Express as an intern laid a crucial foundation. Learning how to program that close to the metal (64-bit zTPF-assembler) as a first programming langauge solidified general concepts that became usefal later on when programming in more abstract languages.
  Since then i've been on a mission to continue to build on that foundation. I am a walking example that programming can be taught to anyone. What makes a good programmer is the ability to think critically to solve problems, and the drive to continue to learn.
  The bottom line is I love to solve problems. Help me to solve yours.

#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
   
   <strong>Java</strong>: I am experienced in a variety of Java API’s and frameworks. I have worked with Spring 4, Spring Boot, JPA (Hibernate) in addition to others. <br/><br/>
   <strong>Development Control</strong>: I have a good knowledge of application life-cycle management and have worked with SVN, Git, Maven, Gradle, Sonar, Jenkins, TeamCity, etc. I have experience with an array of testing tools and technologies.<br/><br/>
   
